esphome:
  name: "esp-smart-thermostat"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  reboot_timeout: 15min

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  domain: ".lan"
  fast_connect: true
  reboot_timeout: 10min
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret ap_ssid
    password: !secret ap_password

captive_portal:

time:
  - platform: sntp
    timezone: "Europe/Sofia"

esp32_ble_tracker:

output:
  - platform: gpio
    pin: GPIO23
    id: led_heat
  
binary_sensor:
  - platform: status
    name: "Thermostat Status"
    
sensor:
  - platform: wifi_signal
    name: "Thermostat WiFi Signal"
    update_interval: 60s
  - platform: uptime
    type: timestamp
    name: "Uptime"

  - platform: atc_mithermometer
    mac_address: "A4:C1:38:34:F2:4A"
    temperature:
      name: "Thermostat Temperature"
      id: temperature
    humidity:
      name: "Thermostat Humidity"
    battery_level:
      name: "Thermostat Sensor Battery"

switch:
  - platform: gpio
    pin: 
      number: GPIO16
    id: relay
    
climate:
  - platform: thermostat
    name: "Thermostat Climate Controller"
    id: climate_thermostat
    sensor: temperature
    min_heating_off_time: 200s
    min_heating_run_time: 300s
    min_idle_time: 30s
    # allows the temp to drop this much, then activates
    heat_deadband: 0.3
    # allow the temp up by this much, then deactivates
    heat_overrun: 0.2
    default_preset: Home
    preset:
      - name: Home
        default_target_temperature_low: '22 °C'
      - name: Away    
        default_target_temperature_low: '20 °C'
    heat_action:
      - switch.turn_on: relay
      - output.turn_on: led_heat
    idle_action:
      - switch.turn_off: relay
      - output.turn_off: led_heat
