esphome:
  name: gate
  friendly_name: Gate
  includes:
    - gate_auth.h
  on_boot:
    priority: -100
    then:
      - lambda: |-
          // Initialize display sensors with stored values
          id(stored_codes_display).publish_state(get_codes_display());
          id(stored_tags_display).publish_state(get_tags_display());
          id(status_message).publish_state("System initialized");

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key
  services:
    - service: add_authorized_code
      variables:
        code: string
        name: string
      then:
        - lambda: |
            add_authorized_code(code, name);
    - service: add_authorized_tag
      variables:
        tag: string
        name: string
      then:
        - lambda: |
            add_authorized_tag(tag, name);
    - service: remove_authorized_code
      variables:
        code: string
      then:
        - lambda: |
            remove_authorized_code(code);
    - service: remove_authorized_tag
      variables:
        tag: string
      then:
        - lambda: |
            remove_authorized_tag(tag);
    - service: clear_all_codes
      then:
        - lambda: |
            clear_all_codes();
    - service: clear_all_tags
      then:
        - lambda: |
            clear_all_tags();

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret ap_ssid
    password: !secret ap_password

captive_portal:

# Web server with version 3 for entity grouping and sorting
web_server:
  version: 3
  auth:
    username: admin
    password: !secret web_password
  sorting_groups:
    - id: access_control_group
      name: "Access Control"
      sorting_weight: 10
    - id: gate_control_group
      name: "Gate Control"
      sorting_weight: 20
    - id: passcode_management_group
      name: "Passcode Management"
      sorting_weight: 30
    - id: status_group
      name: "Status & Diagnostics"
      sorting_weight: 40

# Global variables for storing gate settings
globals:
  - id: gate_action_duration
    type: int
    restore_value: yes
    initial_value: '200'
  - id: last_auth_user
    type: std::string
    restore_value: yes
    initial_value: '"Unknown"'
  - id: enroll_mode_enabled
    type: bool
    restore_value: yes
    initial_value: 'false'
  # Persistent storage for authorized codes (stored as comma-separated strings)
  - id: stored_codes
    type: std::string
    restore_value: yes
    initial_value: '""'
  - id: stored_tags
    type: std::string
    restore_value: yes
    initial_value: '""'

# Output for buzzer feedback
output:
  - platform: ledc
    pin: GPIO32
    id: buzzer_output

# RTTTL for audio feedback
rtttl:
  id: gate_buzzer
  output: buzzer_output

# Gate control relays
switch:
  - platform: gpio
    name: "Gate Relay"
    id: gate_open_relay
    pin:
      number: GPIO17
    internal: true
  
  - platform: gpio
    name: "Unused Relay" 
    id: gate_close_relay
    pin:
      number: GPIO16
    internal: true

  - platform: gpio
    pin: GPIO33
    id: keypad_led
    internal: true

  - platform: template
    name: "Enroll Mode"
    id: enroll_mode
    icon: "mdi:key-chain-variant"
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: CONFIG
    web_server:
      sorting_group_id: access_control_group
      sorting_weight: 10
    turn_on_action:
      - lambda: |
          ESP_LOGI("AUTH", "Enroll mode enabled");
          id(enroll_mode_enabled) = true;
    turn_off_action:
      - lambda: |
          ESP_LOGI("AUTH", "Enroll mode disabled");
          id(enroll_mode_enabled) = false;

button:
  - platform: template
    name: "Clear All Codes"
    id: clear_all_codes_button
    entity_category: CONFIG
    web_server:
      sorting_group_id: access_control_group
      sorting_weight: 90
    on_press:
      - lambda: |
          ESP_LOGI("AUTH", "Clearing all authorized codes");
          clear_all_codes();
          clear_all_tags();
          id(stored_codes_display).publish_state("No codes stored");
          id(stored_tags_display).publish_state("No tags stored");
          id(status_message).publish_state("All codes and tags cleared");

  - platform: template
    name: "Add Passcode"
    id: add_passcode_button
    icon: "mdi:key-plus"
    entity_category: CONFIG
    web_server:
      sorting_group_id: passcode_management_group
      sorting_weight: 30
    on_press:
      - lambda: |
          std::string code = id(new_passcode_input).state;
          std::string name = id(new_passcode_name_input).state;
          
          if (code.length() == 6  && name.length() > 0) {
            add_authorized_code(code, name);
            ESP_LOGI("AUTH", "Added passcode for: %s", name.c_str());
            id(new_passcode_input).publish_state("");
            id(new_passcode_name_input).publish_state("");
            id(status_message).publish_state("Passcode added for " + name);
            id(stored_codes_display).publish_state(get_codes_display());
          } else {
            ESP_LOGW("AUTH", "Can't add a new code: invalid passcode or name");
            id(status_message).publish_state("Error: Code must be 6 digits, name required");
          }

  - platform: template
    name: "Remove Passcode"
    id: remove_passcode_button
    icon: "mdi:key-minus"
    entity_category: CONFIG
    web_server:
      sorting_group_id: passcode_management_group
      sorting_weight: 40
    on_press:
      - lambda: |
          std::string code = id(remove_passcode_input).state;
          
          if (code.length() == 6) {
            remove_authorized_code(code);
            ESP_LOGI("AUTH", "Removed passcode: %s", code.c_str());
            id(remove_passcode_input).publish_state("");
            id(status_message).publish_state("Passcode removed");
            id(stored_codes_display).publish_state(get_codes_display());
          } else {
            ESP_LOGW("AUTH", "Can't remove passcode: invalid format");
            id(status_message).publish_state("Error: Invalid passcode");
          }

  - platform: template
    name: "Add RFID Tag"
    id: add_tag_button
    icon: "mdi:card-plus"
    entity_category: CONFIG
    web_server:
      sorting_group_id: passcode_management_group
      sorting_weight: 50
    on_press:
      - lambda: |
          std::string tag = id(new_tag_input).state;
          std::string name = id(new_tag_name_input).state;
          
          if (tag.length() > 0 && name.length() > 0) {
            add_authorized_tag(tag, name);
            ESP_LOGI("AUTH", "Added tag for: %s", name.c_str());
            id(new_tag_input).publish_state("");
            id(new_tag_name_input).publish_state("");
            id(status_message).publish_state("Tag added for " + name);
            id(stored_tags_display).publish_state(get_tags_display());
          } else {
            ESP_LOGW("AUTH", "Can't add a new tag: invalid tag or name");
            id(status_message).publish_state("Error: Tag ID and name required");
          }

  - platform: template
    name: "Remove RFID Tag"
    id: remove_tag_button
    icon: "mdi:card-minus"
    entity_category: CONFIG
    web_server:
      sorting_group_id: passcode_management_group
      sorting_weight: 60
    on_press:
      - lambda: |
          std::string tag = id(remove_tag_input).state;
          
          if (tag.length() > 0) {
            remove_authorized_tag(tag);
            ESP_LOGI("AUTH", "Removed tag: %s", tag.c_str());
            id(remove_tag_input).publish_state("");
            id(status_message).publish_state("Tag removed");
            id(stored_tags_display).publish_state(get_tags_display());
          } else {
            ESP_LOGW("AUTH", "Can't remove tag: invalid format");
            id(status_message).publish_state("Error: Invalid tag ID");
          }

  - platform: template
    name: "Refresh Lists"
    id: refresh_lists_button
    icon: "mdi:refresh"
    entity_category: CONFIG
    web_server:
      sorting_group_id: passcode_management_group
      sorting_weight: 70
    on_press:
      - lambda: |
          // Update stored codes display
          id(stored_codes_display).publish_state(get_codes_display());
          
          // Update stored tags display
          id(stored_tags_display).publish_state(get_tags_display());
          
          id(status_message).publish_state("Lists refreshed");

# Gate sensor and status indicators
binary_sensor:
  - platform: gpio
    name: "Gate Sensor"
    id: gate_sensor
    pin: 
      number: GPIO27
      mode: INPUT_PULLUP
    device_class: door
    web_server:
      sorting_group_id: status_group
      sorting_weight: 10
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms
    on_state:
      - lambda: |
          if (x) {
            id(gate).position = 1.0;
          } else {
            id(gate).position = 0.0;
          }
          id(gate).publish_state();

cover:
  - platform: template
    name: "Gate"
    id: gate
    device_class: door
    icon: "mdi:gate"
    web_server:
      sorting_group_id: gate_control_group
      sorting_weight: 10
    open_action:
      - switch.turn_on: gate_open_relay
      - delay: 750ms
      - switch.turn_off: gate_open_relay
    close_action:
      - switch.turn_on: gate_open_relay
      - delay: 750ms
      - switch.turn_off: gate_open_relay
    stop_action:
      - switch.turn_on: gate_open_relay
      - delay: 750ms
      - switch.turn_off: gate_open_relay
    

# Text inputs for passcode management
text:
  - platform: template
    name: "New Passcode"
    id: new_passcode_input
    icon: "mdi:numeric"
    optimistic: true
    mode: password
    entity_category: CONFIG
    web_server:
      sorting_group_id: passcode_management_group
      sorting_weight: 10

  - platform: template
    name: "New Passcode Name"
    id: new_passcode_name_input
    icon: "mdi:account"
    optimistic: true
    mode: text
    entity_category: CONFIG
    web_server:
      sorting_group_id: passcode_management_group
      sorting_weight: 20

  - platform: template
    name: "Remove Passcode (Code)"
    id: remove_passcode_input
    icon: "mdi:numeric"
    optimistic: true
    mode: password
    entity_category: CONFIG
    web_server:
      sorting_group_id: passcode_management_group
      sorting_weight: 35
      
  - platform: template
    name: "New RFID Tag ID"
    id: new_tag_input
    icon: "mdi:card-account-details"
    optimistic: true
    mode: text
    entity_category: CONFIG
    web_server:
      sorting_group_id: passcode_management_group
      sorting_weight: 45

  - platform: template
    name: "New RFID Tag Name"
    id: new_tag_name_input
    icon: "mdi:account"
    optimistic: true
    mode: text
    entity_category: CONFIG
    web_server:
      sorting_group_id: passcode_management_group
      sorting_weight: 46

  - platform: template
    name: "Remove RFID Tag (ID)"
    id: remove_tag_input
    icon: "mdi:card-account-details"
    optimistic: true
    mode: text
    entity_category: CONFIG
    web_server:
      sorting_group_id: passcode_management_group
      sorting_weight: 55

# Text sensors for status display
text_sensor:   
  - platform: template
    name: "Last Authenticated User"
    id: last_user
    icon: "mdi:account-check"
    web_server:
      sorting_group_id: status_group
      sorting_weight: 20
    
  - platform: template
    name: "Last Code Entered"
    id: last_code_entered
    icon: "mdi:numeric"
    web_server:
      sorting_group_id: status_group
      sorting_weight: 30

  - platform: template
    name: "Stored Passcodes"
    id: stored_codes_display
    icon: "mdi:key-chain"
    entity_category: DIAGNOSTIC
    web_server:
      sorting_group_id: passcode_management_group
      sorting_weight: 80

  - platform: template
    name: "Stored RFID Tags"
    id: stored_tags_display
    icon: "mdi:card-multiple"
    entity_category: DIAGNOSTIC
    web_server:
      sorting_group_id: passcode_management_group
      sorting_weight: 85

  - platform: template
    name: "Status Message"
    id: status_message
    icon: "mdi:message-alert"
    entity_category: DIAGNOSTIC
    web_server:
      sorting_group_id: status_group
      sorting_weight: 40

# Key collector for PIN codes
key_collector:
  - id: pin_collector
    source_id: gate_wiegand
    min_length: 6
    max_length: 6
    end_keys: "#"
    end_key_required: false
    clear_keys: "*"
    allowed_keys: "0123456789"
    timeout: 10s
    on_progress:
      - lambda: |
          ESP_LOGI("PIN", "PIN entry progress: %s", x.c_str());
    on_result:
      - lambda: |
          ESP_LOGI("PIN", "PIN entered: %s", x.c_str());
          std::string pin_code = x;
          id(last_code_entered).publish_state(pin_code);

          if (id(enroll_mode_enabled)) {
            add_authorized_code(pin_code, "Unknown");
            id(enroll_mode_enabled) = false;
            ESP_LOGI("AUTH", "Code enrolled: %s, disabled enroll mode", pin_code.c_str());
            id(status_message).publish_state("Code enrolled successfully");
            id(stored_codes_display).publish_state(get_codes_display());

            // Success beep
            id(gate_buzzer).play("succ:d=16,o=6,b=160: g,8p,g");
          } else if (check_authorized_code(pin_code)) {
            std::string user_name = get_code_user_name(pin_code);
            ESP_LOGI("AUTH", "Valid PIN code entered by: %s", user_name.c_str());
            id(last_auth_user) = user_name;
            id(last_user).publish_state(user_name);
            
            // Control gate based on current state
            if(id(gate).position) {
              auto call = id(gate).make_call();
              call.set_command_open();
              call.perform();
            } else {
              auto call = id(gate).make_call();
              call.set_command_close();
              call.perform();
            }
                        
            // Success beep
            id(gate_buzzer).play("succ:d=16,o=6,b=160: g,8p,g");
          } else {
            ESP_LOGW("AUTH", "Invalid PIN code entered: %s", pin_code.c_str());
            id(last_user).publish_state("Invalid Code");
            
            // Error beep pattern
            id(gate_buzzer).play("err:d=16,o=6,b=180: c,8p,c,8p,c");
          }
    on_timeout:
      - lambda: |
          ESP_LOGI("PIN", "PIN entry timeout");

# Wiegand interface
wiegand:
  - id: gate_wiegand
    d0: GPIO18   # connect DATA0 here
    d1: GPIO19   # connect DATA1 here

    on_key:
      - lambda: |
          ESP_LOGI("KEY", "Key pressed: %d", x);
          
    on_tag:
      - lambda: |
          ESP_LOGI("TAG", "Tag scanned: %s", x.c_str());
          std::string tag_id = x;

          if (id(enroll_mode_enabled)) {
            add_authorized_tag(tag_id, "Unknown");
            id(enroll_mode_enabled) = false;
            ESP_LOGI("AUTH", "Tag enrolled: %s, disabled enroll mode", tag_id.c_str());
            id(status_message).publish_state("Tag enrolled successfully");
            id(stored_tags_display).publish_state(get_tags_display());

            // Success beep
            id(gate_buzzer).play("succ:d=16,o=6,b=160: g,8p,g");
          } else if (check_authorized_tag(tag_id)) {
            std::string user_name = get_tag_user_name(tag_id);
            ESP_LOGI("AUTH", "Valid tag scanned by: %s", user_name.c_str());
            id(last_auth_user) = user_name;
            id(last_user).publish_state(user_name);
            
            // Control gate based on current state
            if(id(gate).position) {
              auto call = id(gate).make_call();
              call.set_command_open();
              call.perform();
            } else {
              auto call = id(gate).make_call();
              call.set_command_close();
              call.perform();
            }
            
            // Success beep
            id(gate_buzzer).play("succ:d=16,o=6,b=160: g,8p,g");
          } else {
            ESP_LOGW("AUTH", "Invalid tag scanned: %s", tag_id.c_str());
            id(last_user).publish_state("Invalid Tag");
            
            // Error beep pattern
            id(gate_buzzer).play("err:d=16,o=6,b=180: c,8p,c,8p,c");
          }
          
          
    on_raw:
      - lambda: |
          ESP_LOGI("RAW", "Raw data: %d bits, value %llx", bits, value);